spring:
  application:
    name: admin-api
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
  redis:
    host:
      redis://127.0.0.1:7000,
      redis://127.0.0.1:7001,
      redis://127.0.0.1:7002
server:
  port: 8080