spring:
  application:
    name: coupon-consumer
  kafka:
    topic:
      validation-check: validation.check
      coupon-restock: coupon.restock
      coupon-issue: coupon.issue
      event-join: event.join

    bootstrap-servers:
      localhost:9092,
      localhost:9093,
      localhost:9094

coupon:
  restock-quantity: 10

server:
  port: 8083
